name: CI

on:

  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:

  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Restore NuGet packages
      run: nuget restore .

    - name: Build GdbMi
      run: dotnet build .\GdbMi.sln

    - name: Test GdbMi
      run: dotnet test .\GdbMi.sln
